In [ ]:
#######   Titanic dataset is one of the datasets available in sklearn.
#######      1. A Training dataset csv file with X train and Y train data
#######      2. A X test File and you have to predict and submit predictions for this file.




####        My task is Use Logistic Regression and come with predictions.

In [70]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
data_train=pd.read_csv('logistic_train.csv',usecols=['Pclass','SibSp','Parch','Fare','Survived'])
data_test=pd.read_csv('logistic_test.csv',usecols=['Pclass','SibSp','Parch','Fare'])

In [75]:
train=data_train.to_numpy()
train

array([[ 2.    ,  1.    ,  0.    , 26.    ,  1.    ],
       [ 3.    ,  0.    ,  0.    ,  8.05  ,  0.    ],
       [ 2.    ,  0.    ,  0.    , 26.    ,  0.    ],
       ...,
       [ 3.    ,  0.    ,  0.    , 56.4958,  1.    ],
       [ 3.    ,  0.    ,  0.    ,  9.8375,  0.    ],
       [ 3.    ,  1.    ,  0.    , 15.5   ,  1.    ]])

In [78]:
X_train=train[:,0:4]
Y_train=train[:,4]
X_train.reshape(-1,1)

array([[ 2. ],
       [ 1. ],
       [ 0. ],
       ...,
       [ 1. ],
       [ 0. ],
       [15.5]])

In [82]:
model=LogisticRegression()
model.fit(X_train,Y_train)


C:\Users\azam ali\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [83]:
model.predict(data_test)

array([0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       0., 1.])